export const ZONE_TYPES = {
  ENTRY_GATE: 'ENTRY_GATE',
  EXIT_GATE: 'EXIT_GATE',
  SEATING: 'SEATING',
  FOOD: 'FOOD',
  WASHROOM: 'WASHROOM',
  PARKING: 'PARKING',
  MEDICAL: 'MEDICAL',
  CHECKPOINT: 'CHECKPOINT',
  EMERGENCY_EXIT: 'EMERGENCY_EXIT'
};
